### ISSUE TITLE
PDO Driver for SQLite is missing.

### ISSUE THREAD

**Issue by KoljaL** [ethanpil/wordpress-on-replit#1]
After the install i get this message:

```
PDO Driver for SQLite is missing.
Your PHP installtion appears not to have the right PDO drivers loaded. 
These are required for this version of WordPress and the type of database you have specified.
```

Any idea?

**Comment by ethanpil** [comment]
Thanks for pointing this out. Ubuntu added some new versions of the packages and I had to update the script to the new URLs. I have also made some updates to solve SSL issues with the repl proxy.
