### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by TriangularDev** [ethanpil/wordpress-on-replit#13]
Is this secure? Where are the passwords stored? Are they just sitting there encrypted waiting for a hacker to go to the repl and crack them?

**Comment by Studio-Hawaii** [comment]
I do not know how secure this actually is, but I would say that this is powered by wordpress. and im guessing wordpress would have its own security measure's in place.
I do not acutally know where there stored, but I think it might be stored in secrets or somewhere else.
