### ISSUE TITLE
Sorry, you are not allowed to access this page.

### ISSUE THREAD

**Issue by Yash094** [ethanpil/wordpress-on-replit#2]
whenever I try to login to admin page this error occurs. and yes I am using the same acc and password I made during installation

**Comment by p6l** [comment]
did you found a solution ?

**Comment by injoon5** [comment]
I have this issue too.

**Comment by Yash094** [comment]
No

**Comment by eldhosejoys** [comment]
I too have this problem.

**Comment by Yash094** [comment]
Guys I"ve got a temporary solution for this - [solution](https://stackoverflow.com/questions/41880458/wordpress-sorry-you-are-not-allowed-to-edit-this-item/41881463#41881463)

PLEASE MESSAGE ME IF YOU HAVE ANY OTHER PROBLEMS AND IT WILL BE GREAT IF YOU COULD FOLLOW ME.
