### ISSUE TITLE
Install not working?

### ISSUE THREAD

**Issue by gaharrington** [ethanpil/wordpress-on-replit#3]
I have followed the instructions of this repo's README.

After #2 (wget...), I see that the /wordpress dir is present on the repl.it.

Then, I am clicking the "Run" button on the repl.it. (In order to complete the Wordpress installation process.)

No web page ever appears. 

When I click the "Stop" button, I see: "Hmmmm.... We Couldn't Reach Your Repl
Make sure your repl has a port open and is ready to receive HTTP traffic."

Am I misunderstanding something about how to use this repo, or something about repl.it in this application?

**Comment by gaharrington** [comment]
Perhaps a better way to ask my question:

In the README, is step #3 referring to the standard WordPress installation process (which is started by loading the wordpress directory in a browser), or something else related to this repo?

**Comment by shinchanOP** [comment]
If you click the stop button it will stop your repl.
You have to click on run and keep it as it is.

**Comment by Yash094** [comment]
Can you p[ease share a link to your repl ??

**Comment by gaharrington** [comment]
https://replit.com/@gaharrington/MRC-Test-WP

**Comment by Yash094** [comment]
delete all the files and try to run 

wget -O - https://raw.githubusercontent.com/ethanpil/wordpress-on-replit/master/wordpress-on-replit.sh | bash

**Comment by gaharrington** [comment]
Done.

Still getting similar PHP warnings.

**Comment by gaharrington** [comment]
P.S. Thank you for your help! 😁

**Comment by Yash094** [comment]
I made a new server and worked just fine.
are you sure you made a php web server ?

**Comment by gaharrington** [comment]
A new repl works for me too.

Above, when I re-did the wget on my existing repl, I did not check the .replit file. It had dup info.

Once I fixed the .replit file...success!

@shinchanOP THANK YOU so much for your help with this!

**Comment by Yash094** [comment]
No problem ;)

**Comment by ethanpil** [comment]
All of these types of issues should be resolved now with the new Nix version of this script.
